name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'webapp/**'
      - 'package.json'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: lab-uks-entra-webapp
  AZURE_WEBAPP_PACKAGE_PATH: 'webapp'
  NODE_VERSION: '18.x'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: 'webapp/package-lock.json'

    - name: Install dependencies (webapp)
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      run: |
        npm ci --only=production --no-audit

    - name: Install dependencies (root - for tests)
      run: |
        npm ci --only=production

    - name: Run tests (root level)
      run: |
        npm test

    - name: Build application
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      run: |
        npm run build

    - name: Security audit
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      run: |
        npm audit --audit-level high --omit dev || true

    - name: Prepare deployment package
      run: |
        # Create deployment directory
        mkdir -p deployment-package
        
        # Copy webapp contents to deployment package root
        cp -r ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/* deployment-package/
        
        # Ensure node_modules are properly installed in deployment package
        cd deployment-package
        npm ci --only=production --no-audit
        
        # Clean up any unnecessary files
        rm -rf .git* || true
        
        echo "Deployment package contents:"
        ls -la

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: deployment-package

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app
        path: deployment-package

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: deployment-package

    - name: Verify deployment
      run: |
        echo "Application deployed to: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
        curl -f -s -o /dev/null "${{ steps.deploy-to-webapp.outputs.webapp-url }}" || echo "Warning: Health check failed" 