name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'webapp/**'
      - 'package.json'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: lab-uks-entra-webapp
  AZURE_WEBAPP_PACKAGE_PATH: 'webapp'
  NODE_VERSION: '18.x'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: 'webapp/package-lock.json'

    - name: Install dependencies (webapp)
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      run: |
        npm ci --omit=dev --no-audit

    - name: Security audit (non-blocking)
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      run: |
        npm audit --audit-level moderate --omit=dev || echo "Security audit completed with warnings"

    - name: Create deployment package
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      run: |
        # Remove any existing zip
        rm -f ../webapp-deployment.zip
        
        # Create zip with all necessary files
        zip -r ../webapp-deployment.zip . \
          -x "node_modules/.cache/*" \
          -x "*.log" \
          -x "test/*" \
          -x ".git*" \
          -x "coverage/*" \
          -x "*.test.js"
        
        # Verify zip contents
        echo "Deployment package contents:"
        unzip -l ../webapp-deployment.zip | head -20

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: webapp-deployment.zip

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: webapp-deployment.zip

    - name: Verify deployment
      run: |
        echo "Application deployed to: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
        
        # Wait for app to start
        sleep 30
        
        # Health check
        response=$(curl -s -o /dev/null -w "%{http_code}" "${{ steps.deploy-to-webapp.outputs.webapp-url }}/health")
        if [ $response -eq 200 ]; then
          echo "✅ Health check passed"
        else
          echo "⚠️ Health check returned status: $response"
          echo "App may still be starting up..."
        fi

  notify:
    runs-on: ubuntu-latest
    needs: [build, deploy]
    if: always()
    
    steps:
    - name: Notify deployment status
      run: |
        if [ "${{ needs.deploy.result }}" == "success" ]; then
          echo "🎉 Deployment completed successfully!"
          echo "Application URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
        else
          echo "❌ Deployment failed. Check previous steps for errors."
        fi